# 3. VPC内でサブネットを切ってみます．
# さらに今回は "Parametes" セクションを記述することによって，スタック作成時にAZを選択できるようにしてみます．
AWSTemplateFormatVersion: 2010-09-09
Description: This is a stack to create a subnet in some AZ.
Resources:
  # VPC
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: TestVPC

  # Subnet
  TestSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ  # これにより，Parametersで指定したAZを，スタック作成時に参照します．
      VpcId: !Ref TestVPC
      CidrBlock: 10.0.10.0/24  # スタック更新でAZを変更し，かつCIDRが更新前と同じ場合，更新に失敗します．
      Tags:
      - Key: Name
        Value: TestSubnet


# Parametersで設定した各種パラメータの値はマネコン (マネジメントコンソール) 等でのスタック作成時に入力します．
# セキュリティや拡張性の観点からテンプレートにハードコードしたくない情報もここで処理することがよくあります．
Parameters:
  AZ:
    Description: Availability Zone where a subnet is provisioned.
    Type: AWS::EC2::AvailabilityZone::Name  # 変数の型みたいなものです．詳しくはググってください．
    Default: ap-northeast-1a  # デフォルト値を設定します．必須ではありません．
